name: lottokinggpt
description: A new Flutter project.
homepage: https://bitbucket.org/
version: 1.0.0+1
publish_to: none #Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  badges: ^2.0.3
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  custom_navigation_bar: ^0.8.2
  device_info_plus: ^8.0.0
  dio: ^5.1.1
  easy_rich_text: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^5.2.4
  firebase_analytics: ^10.0.4
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_dynamic_links: ^5.0.9
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_flavor: ^3.1.1
  flutter_local_notifications: ^12.0.3
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.0+1
  flutter_zoom_drawer: ^3.0.3
  fluttertoast: ^8.1.2
  go_router: ^7.0.0
  http: ^0.13.5
  image_crop: ^0.4.1
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  kakaomap_webview: ^0.6.2
  logger: ^1.3.0
  lottie: ^2.3.2
  package_info_plus: ^3.0.2
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  retrofit: ^4.0.1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  upgrader: ^6.0.1
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4

# dependency_overrides:
#   transmogrify: ^1.2.0
dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true

  #svg파일 ttf로 변환 : https://www.fluttericon.com/
  #참고 ttf 파일 : https://www.fontspace.com/social-media-color-font-f30260
  fonts:
    - family: SocialMediaIcons
      fonts:
        - asset: assets/fonts/SocialMediaIcons.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/launcher/
    - assets/gif/
    - assets/svg/

# flutter_launcher_icons 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/launcher/icon.png"
  android: true
  ios: true

# flutter_native_splash 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/launcher/splash.png
  color: "#C05228"
  android_12:
    image: assets/launcher/splash.png
    color: "#C05228"
